# Google Cloud Build configuration
# This file allows building via Cloud Console or gcloud

steps:
  # Build the Docker image with build args
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/tunjiax-app:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/tunjiax-app:latest'
      - '--build-arg'
      - 'VITE_GOOGLE_CLIENT_ID=${_VITE_GOOGLE_CLIENT_ID}'
      - '--build-arg'
      - 'VITE_BACKEND_URL=${_VITE_BACKEND_URL}'
      - '--build-arg'
      - 'VITE_ELEVENLABS_AGENT_ID=${_VITE_ELEVENLABS_AGENT_ID}'
      - '.'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/tunjiax-app:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/tunjiax-app:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'tunjiax-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/tunjiax-app:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GCP_PROJECT=$PROJECT_ID,GCP_LOCATION=us-central1'
      - '--add-cloudsql-instances'
      - '${_CLOUD_SQL_INSTANCE}'

# Substitution variables (override these when triggering build)
substitutions:
  _VITE_GOOGLE_CLIENT_ID: '871640164960-pqaanvpmqp85c0kvm13qvv0cbp7nuid2.apps.googleusercontent.com'
  _VITE_BACKEND_URL: 'https://tunjiax-app-xxxxxxxx.run.app'
  _VITE_ELEVENLABS_AGENT_ID: 'agent_6401kdjqx9d6e3dv0efaj08jpv8e'
  _CLOUD_SQL_INSTANCE: 'tunjiax-wallet-482614:us-central1:tunjiax-db'

# Allow substitution variables to be empty or have default values
options:
  substitution_option: 'ALLOW_LOOSE'

# Store the built image
images:
  - 'gcr.io/$PROJECT_ID/tunjiax-app:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/tunjiax-app:latest'
