# TunjiaX-Wallet Cloud Build Configuration
# Triggered by Cloud Build - builds and deploys to Cloud Run
#
# IMPORTANT: Set these substitution variables in Cloud Build Trigger settings:
#   _VITE_GOOGLE_CLIENT_ID
#   _VITE_BACKEND_URL  
#   _VITE_ELEVENLABS_AGENT_ID
#   _ELEVENLABS_SECRET
#   _DB_PASSWORD
#   _JWT_SECRET
#   _CLOUD_SQL_CONNECTION

steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/tunjiax-wallet:latest'
      - '--build-arg'
      - 'VITE_GOOGLE_CLIENT_ID=${_VITE_GOOGLE_CLIENT_ID}'
      - '--build-arg'
      - 'VITE_BACKEND_URL=${_VITE_BACKEND_URL}'
      - '--build-arg'
      - 'VITE_ELEVENLABS_AGENT_ID=${_VITE_ELEVENLABS_AGENT_ID}'
      - '.'

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    args: ['push', 'gcr.io/$PROJECT_ID/tunjiax-wallet:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'tunjiax-wallet'
      - '--image=gcr.io/$PROJECT_ID/tunjiax-wallet:latest'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=4Gi'
      - '--cpu=4'
      - '--set-env-vars=GCP_PROJECT=$PROJECT_ID,GCP_LOCATION=us-central1,GOOGLE_CLIENT_ID=${_VITE_GOOGLE_CLIENT_ID},CLOUD_SQL_CONNECTION_NAME=${_CLOUD_SQL_CONNECTION}'
      - '--set-secrets=ELEVENLABS_CUSTOM_LLM_SECRET=elevenlabs-secret:latest,DB_PASSWORD=db-password:latest,JWT_SECRET_KEY=jwt-secret:latest'
      - '--add-cloudsql-instances=${_CLOUD_SQL_CONNECTION}'

# Default substitutions (non-sensitive only)
substitutions:
  _VITE_BACKEND_URL: 'https://tunjiax-wallet-871640164960.us-central1.run.app'
  _CLOUD_SQL_CONNECTION: 'tunjiax-wallet-482614:us-central1:tunjiax-db'

images:
  - 'gcr.io/$PROJECT_ID/tunjiax-wallet:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  substitution_option: 'ALLOW_LOOSE'
