# TunjiaX-Wallet Cloud Build Configuration
# Triggered by Cloud Build - builds and deploys to Cloud Run

steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/tunjiax-wallet:latest'
      - '--build-arg'
      - 'VITE_GOOGLE_CLIENT_ID=871640164960-pqaanvpmqp85c0kvm13qvv0cbp7nuid2.apps.googleusercontent.com'
      - '--build-arg'
      - 'VITE_BACKEND_URL=https://tunjiax-wallet-871640164960.us-central1.run.app'
      - '--build-arg'
      - 'VITE_ELEVENLABS_AGENT_ID=agent_6401kdjqx9d6e3dv0efaj08jpv8e'
      - '.'

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    args: ['push', 'gcr.io/$PROJECT_ID/tunjiax-wallet:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'tunjiax-wallet'
      - '--image=gcr.io/$PROJECT_ID/tunjiax-wallet:latest'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=4Gi'
      - '--cpu=4'
      - '--set-env-vars=GCP_PROJECT=$PROJECT_ID,GCP_LOCATION=us-central1,GOOGLE_CLIENT_ID=871640164960-pqaanvpmqp85c0kvm13qvv0cbp7nuid2.apps.googleusercontent.com,ELEVENLABS_CUSTOM_LLM_SECRET=5424ef17a900644bf24b1444036c64947509fbd4632099feb0a0ccddac325c78f17a900644bf24b1444036c64947509fbd4632099feb0a0ccddac325c78,DB_PASSWORD=TunjiaX2025Secure!,JWT_SECRET_KEY=84e5994ee71522b9ae570047552eb1ae95d5516a9b2aadb054faea64a8514006,CLOUD_SQL_CONNECTION_NAME=tunjiax-wallet-482614:us-central1:tunjiax-db'
      - '--add-cloudsql-instances=tunjiax-wallet-482614:us-central1:tunjiax-db'

images:
  - 'gcr.io/$PROJECT_ID/tunjiax-wallet:latest'

options:
  logging: CLOUD_LOGGING_ONLY
